# SPDX-License-Identifier: Apache-2.0
services:
  zyra:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["/bin/bash", ".devcontainer/entrypoint.sh"]
    profiles: ["dev"]
    volumes:
      - .:/app
      - ./data/uploads:/data/uploads
    env_file:
      - .env   # ✅ Loads all environment variables from .env
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      ZYRA_API_HOST: 0.0.0.0
      ZYRA_API_PORT: 8000
      ZYRA_UPLOAD_DIR: /data/uploads
      ZYRA_MIN_DISK_MB: 100
      ZYRA_REQUIRE_FFMPEG: 0
      ZYRA_USE_REDIS: 1
      ZYRA_REDIS_URL: redis://redis:6379/0
      ZYRA_AUTOSTART_API: 1
      ZYRA_AUTOSTART_RQ: 1
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/ready"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    depends_on:
      - redis

  redis:
    image: redis:7
    profiles: ["dev"]
    ports:
      - "6379:6379"
