# SPDX-License-Identifier: Apache-2.0
# Example usage for the zyra image.
# Default image runs the API server; this compose service overrides
# the entrypoint to expose the CLI for ad-hoc runs.

services:
  zyra:
    image: ghcr.io/noaa-gsl/zyra:${ZYRA_TAG:-latest}
    restart: "no"
    entrypoint: ["zyra"]
    environment:
      - DATA_DIR=/data
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - TZ=${TZ:-UTC}
    volumes:
      - ./workflows:/workflows:ro
      - ./data:/data
    # Default shows help; override per-invocation with `docker compose run`.
    command: ["--help"]
    # Optional: match host UID/GID to avoid permission issues on bind mounts (Linux)
    # user: "${UID:-1000}:${GID:-1000}"
