# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
metadata:
  name: zyra-api-secrets
  namespace: zyra
type: Opaque
stringData:
  # Replace with a secure value or create via kubectl to avoid committing secrets:
  #   kubectl -n zyra create secret generic zyra-api-secrets \
  #     --from-literal=ZYRA_API_KEY=<your-secret>
  ZYRA_API_KEY: "replace-me"

