name: DCO Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dco:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify commit sign-offs (DCO)
        uses: crazy-max/ghaction-dco@v3
        with:
          # Set to true to add a PR comment; default is true
          comment: true
          # Fail the job if sign-off is missing
          fail: true

