name: Build Docker Images (matrix)

on:
  pull_request:
    paths:
      - 'docker/**'
      - 'Dockerfile'
      - 'pyproject.toml'
      - '.github/workflows/docker-matrix.yml'
  workflow_dispatch:

concurrency:
  group: docker-matrix-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.target.name }} (WITH_WGRIB2=${{ matrix.target.with_wgrib2 }})
    runs-on: ubuntu-latest
    if: (github.event_name != 'pull_request' || github.event.pull_request.draft == false) && (github.event_name != 'pull_request' || ((matrix.target.name == 'zyra' && matrix.target.with_wgrib2 == 'source') || (matrix.target.name == 'zyra-scheduler' && matrix.target.with_wgrib2 == 'none')))
    strategy:
      fail-fast: false
      matrix:
        target:
          - { name: "zyra", file: "docker/zyra/Dockerfile", with_wgrib2: "source" }
          - { name: "zyra", file: "docker/zyra/Dockerfile", with_wgrib2: "none" }
          - { name: "zyra-scheduler", file: "docker/zyra-scheduler/Dockerfile", with_wgrib2: "none" }
          - { name: "zyra-scheduler", file: "docker/zyra-scheduler/Dockerfile", with_wgrib2: "source" }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.target.file }}
          platforms: linux/amd64
          push: false
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            WITH_WGRIB2=${{ matrix.target.with_wgrib2 }}
          tags: test/${{ matrix.target.name }}:${{ matrix.target.with_wgrib2 }}
